#!/usr/bin/env node
// Real check for the "vo-model-correct" rule. Confirms audio_meta.json's own recorded
// model_id, not console output from generation time (which nobody re-reads later) and not
// this project's general assumption that VO is always eleven_v3 -- that assumption is
// exactly what let the wrong-model bug ship once already.
//
// audio_meta.json did not persist model_id at all until generate_vo_single_take.mjs was
// patched alongside this check (see that script's own comment) -- an episode generated
// before that fix will correctly report "field missing," not a false pass. That's an
// honest signal (predates the fix), not a bug in this check.
//
// Usage: node check_vo_model.mjs --project-dir hyperframes-<episode> --docs-root <repo-root> [--expected-model eleven_v3]

import { existsSync, readFileSync } from "node:fs";
import path from "node:path";

function parseArgs(argv) {
  const out = { expectedModel: "eleven_v3" };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--project-dir") out.projectDir = argv[++i];
    else if (argv[i] === "--docs-root") out.docsRoot = argv[++i];
    else if (argv[i] === "--expected-model") out.expectedModel = argv[++i];
  }
  if (!out.projectDir) throw new Error("missing --project-dir <path>");
  out.projectDir = path.resolve(out.projectDir);
  return out;
}

function main() {
  const { projectDir, expectedModel } = parseArgs(process.argv.slice(2));
  const audioMetaPath = path.join(projectDir, "audio_meta.json");

  console.log(`\nVO model check for "${path.basename(projectDir)}" (expecting "${expectedModel}")`);

  if (!existsSync(audioMetaPath)) {
    console.error(`✗ FAIL -- no audio_meta.json found at ${audioMetaPath}.`);
    process.exit(1);
  }

  let audioMeta;
  try {
    audioMeta = JSON.parse(readFileSync(audioMetaPath, "utf-8"));
  } catch {
    console.error(`✗ FAIL -- audio_meta.json exists but failed to parse as JSON.`);
    process.exit(1);
  }

  if (!audioMeta.model_id) {
    console.error(`✗ FAIL -- audio_meta.json has no model_id field recorded.`);
    console.error(`  Either this episode's VO predates generate_vo_single_take.mjs's model_id`);
    console.error(`  recording fix, or VO was generated by a different path (the media-use`);
    console.error(`  wrapper, which still hardcodes eleven_multilingual_v2 with no override --`);
    console.error(`  regenerate VO via /thataipm-vo to get a real, checkable record.`);
    process.exit(1);
  }

  if (audioMeta.model_id !== expectedModel) {
    console.error(`✗ FAIL -- audio_meta.json records model_id="${audioMeta.model_id}", expected "${expectedModel}".`);
    process.exit(1);
  }

  console.log(`✓ PASS -- audio_meta.json confirms model_id="${audioMeta.model_id}".`);
  process.exit(0);
}

main();
